import { Category, Membership, MembershipStatus } from "./types";

export const POPULAR_PROVIDERS: Record<Category, string[]> = {
  [Category.AIRLINES]: [
    "United Airlines",
    "Delta Air Lines",
    "American Airlines",
    "Southwest Airlines",
    "Lufthansa",
    "Emirates",
    "Qatar Airways",
    "British Airways",
  ],
  [Category.HOTELS]: [
    "Marriott Bonvoy",
    "Hilton Honors",
    "Hyatt World",
    "IHG One Rewards",
    "Accor Live Limitless",
    "Wyndham Rewards",
  ],
  [Category.CABS]: [
    "Uber",
    "Lyft",
    "Hertz",
    "Avis",
    "Sixt",
  ],
  [Category.ALL]: [],
};

export const PROGRAMS_MAP: Record<string, string> = {
  "United Airlines": "MileagePlus",
  "Delta Air Lines": "SkyMiles",
  "American Airlines": "AAdvantage",
  "Marriott Bonvoy": "Bonvoy Rewards",
  "Hilton Honors": "Honors",
  "Hyatt World": "World of Hyatt",
};

export const CATEGORIES = [
  Category.ALL,
  Category.AIRLINES,
  Category.HOTELS,
  Category.CABS,
];

export const INITIAL_MEMBERSHIPS: Membership[] = [
  {
    id: "1",
    providerName: "United Airlines",
    category: Category.AIRLINES,
    membershipId: "UA-9988776655",
    status: MembershipStatus.VERIFIED,
    isPrimary: true,
    logoUrl: "./companyLogos/United Airlines.png",
    frequentFlyerProgram: "MileagePlus",
  },
  {
    id: "2",
    providerName: "Marriott Bonvoy",
    category: Category.HOTELS,
    membershipId: "MB-123456789",
    status: MembershipStatus.PENDING,
    isPrimary: true,
    logoUrl: "./companyLogos/Marriott Bonvoy.png",
    tier: "Gold Elite",
  },
  {
    id: "3",
    providerName: "Uber",
    category: Category.CABS,
    membershipId: "UB-TRAVEL-001",
    status: MembershipStatus.ACTION_REQUIRED,
    isPrimary: true,
    logoUrl: "./companyLogos/uber.png",
    corporateCode: "CORP-AMEX-2024",
  },

  // realistic secondary memberships

  {
    id: "4",
    providerName: "Delta Air Lines",
    category: Category.AIRLINES,
    membershipId: "DL-347829104",
    status: MembershipStatus.VERIFIED,
    isPrimary: false,
    logoUrl: "./companyLogos/Delta Air Lines.png",
    frequentFlyerProgram: "SkyMiles",
  },
  {
    id: "5",
    providerName: "Hilton Honors",
    category: Category.HOTELS,
    membershipId: "HH-55892013",
    status: MembershipStatus.VERIFIED,
    isPrimary: false,
    logoUrl: "./companyLogos/Hilton Honors.png",
    tier: "Silver",
  },
  {
    id: "6",
    providerName: "Avis",
    category: Category.CABS,
    membershipId: "AV-EMP-20491",
    status: MembershipStatus.PENDING,
    isPrimary: false,
    logoUrl: "./companyLogos/Avis.png",
    corporateCode: "CORP-TRAVEL-01",
  },
];

// export const INITIAL_MEMBERSHIPS: Membership[] = [
//   {
//     id: "1",
//     providerName: "United Airlines",
//     category: Category.AIRLINES,
//     membershipId: "UA-9988776655",
//     status: MembershipStatus.VERIFIED,
//     isPrimary: true,
//     logoUrl: "./companyLogos/United Airlines.png",
//     frequentFlyerProgram: "MileagePlus",
//   },
//   {
//     id: "2",
//     providerName: "Marriott Bonvoy",
//     category: Category.HOTELS,
//     membershipId: "MB-123456789",
//     status: MembershipStatus.PENDING,
//     isPrimary: true,
//     logoUrl: "./companyLogos/Marriott Bonvoy.png",
//     tier: "Gold Elite",
//   },
//   {
//     id: "3",
//     providerName: "Uber",
//     category: Category.CABS,
//     membershipId: "UB-TRAVEL-001",
//     status: MembershipStatus.ACTION_REQUIRED,
//     isPrimary: true,
//     logoUrl: "./companyLogos/uber.png",
//     corporateCode: "CORP-AMEX-2024",
//   },

//   // ---- Airlines ----
//   {
//     id: "4",
//     providerName: "Delta Air Lines",
//     category: Category.AIRLINES,
//     membershipId: "DL-4455667788",
//     status: MembershipStatus.VERIFIED,
//     isPrimary: false,
//     logoUrl: "./companyLogos/Delta Air Lines.png",
//     frequentFlyerProgram: "SkyMiles",
//   },
//   {
//     id: "5",
//     providerName: "American Airlines",
//     category: Category.AIRLINES,
//     membershipId: "AA-1122334455",
//     status: MembershipStatus.PENDING,
//     isPrimary: false,
//     logoUrl: "./companyLogos/American Airlines.png",
//     frequentFlyerProgram: "AAdvantage",
//   },
//   {
//     id: "6",
//     providerName: "Lufthansa",
//     category: Category.AIRLINES,
//     membershipId: "LH-90807060",
//     status: MembershipStatus.VERIFIED,
//     isPrimary: false,
//     logoUrl: "./companyLogos/Lufthansa.png",
//     frequentFlyerProgram: "Miles & More",
//   },
//   {
//     id: "7",
//     providerName: "Emirates",
//     category: Category.AIRLINES,
//     membershipId: "EK-3344556677",
//     status: MembershipStatus.ACTION_REQUIRED,
//     isPrimary: false,
//     logoUrl: "./companyLogos/Emirates.png",
//     frequentFlyerProgram: "Skywards",
//   },

//   // ---- Hotels ----
//   {
//     id: "8",
//     providerName: "Hilton Honors",
//     category: Category.HOTELS,
//     membershipId: "HH-5566778899",
//     status: MembershipStatus.VERIFIED,
//     isPrimary: false,
//     logoUrl: "./companyLogos/Hilton Honors.png",
//     tier: "Diamond",
//   },
//   {
//     id: "9",
//     providerName: "Hyatt World",
//     category: Category.HOTELS,
//     membershipId: "HY-1029384756",
//     status: MembershipStatus.PENDING,
//     isPrimary: false,
//     logoUrl: "./companyLogos/Hyatt World.png",
//     tier: "Explorist",
//   },
//   {
//     id: "10",
//     providerName: "IHG One Rewards",
//     category: Category.HOTELS,
//     membershipId: "IHG-6677889900",
//     status: MembershipStatus.VERIFIED,
//     isPrimary: false,
//     logoUrl: "./companyLogos/IHG One Rewards.png",
//     tier: "Platinum Elite",
//   },
//   {
//     id: "11",
//     providerName: "Accor Live Limitless",
//     category: Category.HOTELS,
//     membershipId: "ALL-5566443322",
//     status: MembershipStatus.ACTION_REQUIRED,
//     isPrimary: false,
//     logoUrl: "./companyLogos/Accor Live Limitless.png",
//     tier: "Silver",
//   },

//   // ---- Cabs / Car rentals ----
//   {
//     id: "12",
//     providerName: "Lyft",
//     category: Category.CABS,
//     membershipId: "LYFT-88990011",
//     status: MembershipStatus.VERIFIED,
//     isPrimary: false,
//     logoUrl: "./companyLogos/Lyft.png",
//     corporateCode: "CORP-LYFT-2024",
//   },
//   {
//     id: "13",
//     providerName: "Hertz",
//     category: Category.CABS,
//     membershipId: "HZ-33441122",
//     status: MembershipStatus.PENDING,
//     isPrimary: false,
//     logoUrl: "./companyLogos/Hertz.png",
//     corporateCode: "HZ-CORP-INDIA",
//   },
//   {
//     id: "14",
//     providerName: "Avis",
//     category: Category.CABS,
//     membershipId: "AV-77889900",
//     status: MembershipStatus.VERIFIED,
//     isPrimary: false,
//     logoUrl: "./companyLogos/Avis.png",
//     corporateCode: "AVIS-BIZ-2025",
//   },
//   {
//     id: "15",
//     providerName: "Sixt",
//     category: Category.CABS,
//     membershipId: "SIXT-44556677",
//     status: MembershipStatus.ACTION_REQUIRED,
//     isPrimary: false,
//     logoUrl: "./companyLogos/Sixt.png",
//     corporateCode: "SIXT-CORP",
//   },
// ];

